# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3d4a0f37aafc5e4c0e7c3e0588b450c609f6789bff10296bd8ebb884e987f1fc23e5764d27073e8015ccebac4db02829b29f83ddef2bf42ef2412fd406d2f52

test:
  secret_key_base: 553a85a3525f7378a8888388f0c39be074b1c263bd2549e05f44efd0562194257dc06b77f6127a01b9a010cba1b299fb236da9f0ae4c2ce5b0dc6e9c6c195741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
